default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= Rails.application.credentials.DATABASE_URL %>
  prepared_statements: false # Required for Supabase transaction pooler (pgBouncer)

development:
  <<: *default

test:
  <<: *default
  database: therasaurus_rails_test

production:
  <<: *default
